# Generated by Django 5.2.2 on 2025-06-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
    ]
